### ISSUE TITLE
Initialize intl-tel-input-rails

### ISSUE THREAD

**Issue by bntzio** [ispyropoulos/intl-tel-input-rails#11]
Hey,

I just installed the gem, but I don't see how to get running the flags in the **README**, what I did:
1. Add the gem to my Gemfile `gem 'intl-tel-input-rails'`
2. Install it `bundle`
3. Require it in my application.js file `//= require intlTelInput`
4. Import it in my application.scss file `@import "intlTelInput";`
5. Add the _phone_ id into my input field as well as the _tel_ type (as indicated on the original plugin)

Nothing happens, how do I get this running? I can't see the flags or even the dropdown showing on my input field, why?

Note: I also did initialize the field with jQuery `$("#phone").intlTelInput();` and nothing as well.

I'd really appreciate your help! 😃 

Thank you!

**Comment by JasonMrX** [comment]
Hi @bntzio 

I think you have to override the image flag path as stated [here](https://github.com/jackocnr/intl-tel-input#getting-started).

We are actually working on integrating this into the gem, so that you might not have to worry about this any more in the next release 

Hope this help

Jason
