### ISSUE TITLE
Flags are not displayed

### ISSUE THREAD

**Issue by gaetanm** [ispyropoulos/intl-tel-input-rails#7]
I'm using Rails 3.2 and I've just installed your gem. I don't understand why the flag icons are not displayed on my page:
![screen shot 2015-10-23 at 16 57 51](https://cloud.githubusercontent.com/assets/2548394/10696472/618a3a08-79a8-11e5-84c1-f4cd3f6f9b19.png)

Any idea? I put all the directives as indicated in the README.

**Comment by gaetanm** [comment]
Okey it's because my app uses CSS, not Sass, while this gem only provides a scss file.

**Comment by Apokly** [comment]
Thanks for the answer. I've tried to to rename the 'intlTelInput.scss' file into a 'intlTelInput.css' and to not require 'sass-rails' on gemspec, flags are not displaying in host application. My host application includes 'sass-rails'.

Could we have more explications about that.
Thank you.

**Comment by DannyBen** [comment]
Hey - I see this is an old ticket, but I have the exact same problem - flags are not showing, and I DO use scss and added `@import "intlTelInput";` to my main scss file.

Not sure how to debug this further, but I hope to find a solution since other than this, the plugin works great.

**Comment by ispyropoulos** [comment]
@DannyBen this problem was fixed a few months back, on master, and also in the latest gem release. Closing.
