### ISSUE TITLE
utils.js not loading

### ISSUE THREAD

**Issue by lorenzsell** [ispyropoulos/intl-tel-input-rails#8]
I am able to initialize the plug in, but utils.js isn't loading and so formating and validation of number is not happening.  Am I missing something here?

Thank you.

**Comment by kozhin** [comment]
I had the same problem.
As described here: https://github.com/jackocnr/intl-tel-input#options

*utilsScript
Type: String Default: "" Example: "lib/libphonenumber/build/utils.js"
Enable formatting/validation etc. by specifying the path to the included utils.js script, which is fetched only when the page has finished loading (on window.load) to prevent blocking. See Utilities Script for more information. Note that if you're lazy loading the plugin script itself (intlTelInput.js) this will not work and you will need to use the loadUtils method instead.*

So I included utils.min.js in my application separately using utilsScript option.

```ruby
<% content_for :footer do %>
        <!-- International Telephones plugin code -->
        <script type="text/javascript">
            $('input[type=tel]').intlTelInput({
                defaultCountry: "ru",
                preferredCountries: ["ru", "by", "kz"],
                nationalMode: false,
                utilsScript: "<%= asset_path('/static/utils.min.js') %>"
            });
        </script>
<% end %>
```

**Comment by nguyenj** [comment]
I don't think you need to add `utilsScript` attribute if you're already doing this:

```
//= require libphonenumber/utils
```
