### ISSUE TITLE
update the plugin

### ISSUE THREAD

**Issue by JasonMrX** [ispyropoulos/intl-tel-input-rails#9]
Hi Ilias,

I've yanked the gem on Rubygem.org. As I mentioned, may I open up a pull request to update to plugin to the newest version? There have been major changes in the plugin since the the last release of the gem. 

Again, I apologize for my ignorance of the convention of the community.

Jason

**Comment by ispyropoulos** [comment]
Sure. Please open a pull request with your updates/fixes.

**Comment by GoWang** [comment]
Hi Ilias,

@JasonMrX and I have opened a new pull request. Would you mind having a look at the updates. Thanks.

Rong
